"""Full-utterance residual-buzz attribution for the trained LYKENOX v4.2 vocoder.

The persistent v4.2 run materially improves full-utterance oracle quality versus v4.1,
but listening still reports a residual periodic metallic/chillido component.  This gate
must assign that remaining artifact before any new training is authorized.

V4.2 separates its sample-rate representation into:

    mel envelope path + sigmoid(source_gate(mel)) * source_features

This diagnostic reproduces the trained v4.2 forward exactly, then scales only the complete
post-stem source contribution at that integration point.  It therefore answers a narrower
question than the historical v4.1 harmonic-gain sweep: is the remaining v4.2 buzz still
entering through the transformed source branch, or is it being generated by the downstream
conditioned filter even when that branch is removed?

No checkpoint is mutated, no training occurs, and no post-hoc loudness normalization is
applied.  A single complete held-out oracle-conditioned utterance is used first to keep the
listening decision bounded.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path

import soundfile as sf
import torch
import torch.nn.functional as F

from lykenox_voice_engine.models.speech import LykenoxSpeechConfig
from lykenox_voice_engine.models.vocoder import VOCODER_GENERATOR_V4_2_ARCHITECTURE
from lykenox_voice_engine.training.speech_aligned_data import (
    LykenoxAlignedSpeechDataset,
    collate_aligned_speech,
    find_clean_duration_root,
)
from lykenox_voice_engine.training.speech_reference_free_failure_isolation_audit import (
    _wave_metrics,
)
from lykenox_voice_engine.training.speech_vocoder_v4_2_artifact import load_v4_2_checkpoint


AUDIT_VERSION = "vocoder-v4-2-full-utterance-residual-source-path-ablation-v1"
SOURCE_PATH_GAINS = (1.0, 0.75, 0.50, 0.25, 0.0)


def _atomic_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    os.replace(temporary, path)


def _forward_with_source_path_gain(
    generator,
    mel: torch.Tensor,
    f0_hz: torch.Tensor,
    voiced: torch.Tensor,
    *,
    source_path_gain: float,
) -> torch.Tensor:
    """Reproduce v4.2 while scaling only its transformed source-path contribution."""

    if source_path_gain < 0.0:
        raise ValueError("source_path_gain must be non-negative")
    generator._validate_inputs(mel, f0_hz, voiced)
    batch, mel_frames, _ = mel.shape
    samples = int(mel_frames) * generator.config.hop_length

    mel_frames_ch = mel.transpose(1, 2)
    conditioning_frames = generator.frame_conditioner(mel_frames_ch)
    conditioning_samples = F.interpolate(
        conditioning_frames,
        size=samples,
        mode="linear",
        align_corners=False,
    )

    f0_samples = F.interpolate(
        f0_hz.unsqueeze(1),
        size=samples,
        mode="linear",
        align_corners=False,
    ).clamp_min(0.0)
    voiced_samples = F.interpolate(
        voiced.unsqueeze(1),
        size=samples,
        mode="linear",
        align_corners=False,
    ).clamp(0.0, 1.0)
    harmonic_weight_frames = generator._harmonic_weight_frames(mel)
    harmonic_weights_samples = F.interpolate(
        harmonic_weight_frames,
        size=samples,
        mode="linear",
        align_corners=False,
    )
    harmonic = generator._harmonic_source(
        f0_samples,
        voiced_samples,
        harmonic_weights_samples,
    )
    noise = generator._aperiodic_source(
        batch,
        samples,
        device=mel.device,
        dtype=mel.dtype,
    )
    noise = noise * (0.08 + 0.92 * (1.0 - voiced_samples))
    log_f0 = torch.log1p(f0_samples) / math.log1p(500.0)

    source = torch.cat(
        [harmonic, voiced_samples, log_f0, noise],
        dim=1,
    )
    source_features = generator.source_stem(source)
    source_gate = torch.sigmoid(generator.source_gate(conditioning_samples))
    envelope_path = generator.mel_to_hidden(conditioning_samples)
    source_path = source_gate * source_features
    x = envelope_path + float(source_path_gain) * source_path

    skips: list[torch.Tensor] = []
    for block in generator.blocks:
        x, skip = block(x, conditioning_samples)
        skips.append(skip)
    x = torch.stack(skips, dim=0).sum(dim=0) / math.sqrt(float(len(skips)))
    raw_waveform = generator.post(F.leaky_relu(x, negative_slope=0.1))
    filtered = F.conv1d(
        raw_waveform,
        generator.output_highpass_fir.to(
            device=raw_waveform.device,
            dtype=raw_waveform.dtype,
        ),
        padding=generator.highpass_kernel_size // 2,
    )
    waveform = torch.tanh(filtered).squeeze(1)
    if tuple(waveform.shape) != (batch, samples):
        raise RuntimeError("v4.2 source-path ablation changed waveform length contract")
    return waveform


def run_v4_2_residual_source_path_ablation(root: Path) -> dict[str, object]:
    root = Path(root).resolve()
    checkpoint = (
        root
        / "models"
        / "lykenox_identity"
        / "training"
        / "vocoder_source_filter_v4_2"
        / "best.pt"
    )
    if not checkpoint.exists():
        raise FileNotFoundError(f"Persistent v4.2 best checkpoint not found: {checkpoint}")

    output_dir = (
        root
        / "models"
        / "lykenox_identity"
        / "evaluation"
        / "vocoder_v4_2_residual_source_path_ablation_v1"
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / "residual_source_path_ablation_report.json"

    torch.set_num_threads(max(1, min(4, torch.get_num_threads())))
    generator, _discriminator, payload = load_v4_2_checkpoint(checkpoint)
    generator.cpu().eval()
    identity_exact = (
        generator.architecture == VOCODER_GENERATOR_V4_2_ARCHITECTURE
        and payload.get("generator_architecture") == VOCODER_GENERATOR_V4_2_ARCHITECTURE
    )
    if not identity_exact:
        raise RuntimeError("Residual source-path audit requires the persistent v4.2 identity")

    speech_config = LykenoxSpeechConfig()
    duration_root = find_clean_duration_root(root)
    dataset = LykenoxAlignedSpeechDataset(
        root,
        "val",
        speech_config,
        duration_root=duration_root,
        include_pitch_targets=True,
    )
    item = dataset[0]
    batch = collate_aligned_speech([item]).to("cpu")
    if batch.f0_hz is None or batch.voiced is None:
        raise RuntimeError("Residual source-path audit requires target F0/voicing")

    frames = int(batch.mel_lengths[0])
    mel = batch.mel[:, :frames]
    f0_hz = batch.f0_hz[:, :frames]
    voiced = batch.voiced[:, :frames]

    with torch.inference_mode():
        baseline = generator(mel, f0_hz, voiced)
        reproduced = _forward_with_source_path_gain(
            generator,
            mel,
            f0_hz,
            voiced,
            source_path_gain=1.0,
        )
    reproduction_max_delta = float((baseline - reproduced).abs().max())
    reproduction_exact = reproduction_max_delta <= 1e-7
    if not reproduction_exact:
        raise RuntimeError("Residual source-path diagnostic does not reproduce v4.2 exactly")

    variants: list[dict[str, object]] = []
    with torch.inference_mode():
        for gain in SOURCE_PATH_GAINS:
            waveform = _forward_with_source_path_gain(
                generator,
                mel,
                f0_hz,
                voiced,
                source_path_gain=gain,
            )[0].detach().cpu().to(torch.float32).contiguous()
            if not bool(torch.isfinite(waveform).all()):
                raise RuntimeError(f"Non-finite waveform at source_path_gain={gain}")
            label = str(gain).replace(".", "p")
            wav_path = output_dir / f"source_path_gain_{label}.wav"
            sf.write(
                str(wav_path),
                waveform.numpy(),
                generator.config.sample_rate,
                subtype="PCM_16",
            )
            variants.append(
                {
                    "source_path_gain": gain,
                    "wav_path": str(wav_path),
                    **_wave_metrics(waveform, generator.config.sample_rate),
                }
            )

    report: dict[str, object] = {
        "status": "needs_listening",
        "audit_version": AUDIT_VERSION,
        "device": "cpu",
        "checkpoint": str(checkpoint),
        "generator_architecture": payload.get("generator_architecture"),
        "v4_2_identity_exact": identity_exact,
        "utterance_id": str(item["utterance_id"]),
        "text": str(item["text"]),
        "teacher_mel_frames": frames,
        "duration_seconds": round(
            frames * generator.config.hop_length / generator.config.sample_rate,
            4,
        ),
        "target_voiced_fraction": round(float(voiced.mean()), 6),
        "baseline_reproduction_exact": reproduction_exact,
        "baseline_reproduction_max_delta": reproduction_max_delta,
        "persistent_training_mutated": False,
        "persistent_training_restarted": False,
        "variants": variants,
        "interpretation": (
            "If the residual metallic/chillido artifact falls materially as source_path_gain "
            "decreases while intelligibility remains useful, the remaining v4.2 defect still "
            "enters primarily through the transformed source branch and the next revision should "
            "constrain/gate that branch rather than increase generic filter capacity. If the "
            "artifact remains at gain 0.0, the downstream mel-conditioned residual/skip filter or "
            "waveform projection is generating the defect independently of explicit source-path "
            "authority. If lowering gain removes both buzz and voice, the model remains dependent "
            "on source leakage and a runtime gain tweak is not an acceptable fix."
        ),
        "next_gate": "listen_v4_2_residual_source_path_ablation_before_any_new_training",
    }
    _atomic_json(report_path, report)
    report["report_path"] = str(report_path)
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    print(
        json.dumps(
            run_v4_2_residual_source_path_ablation(args.root),
            indent=2,
            ensure_ascii=False,
        )
    )


if __name__ == "__main__":
    main()
