"""Scoped train-and-listen authorization after v2 directional failure.

LYX-POL-001 remains authoritative.  The only new allowance is a deterministic, read-only
pre-training calibration that selects one fixed positive loss-weight vector from owned
train/validation gradient directions before any model optimizer exists.  Those weights are
then frozen into run config/checkpoint and may not change during training or resume.
"""

from __future__ import annotations


CONTRACT_VERSION = "owned-minimum-phase-bounded-train-and-listen-contract-v2"
POLICY_ID = "LYX-POL-001"
POLICY_VERSION = "1.0"
CPU_ONLY = True
TRAIN_AND_LISTEN_AUTHORIZED = True
MAX_UPDATES_AUTHORIZED = 400
DIRECTIONAL_PRETRAIN_CALIBRATION_REQUIRED = True
CALIBRATION_BEFORE_MODEL_OPTIMIZER_REQUIRED = True
CALIBRATED_WEIGHTS_FIXED_FOR_RUN = True
CALIBRATED_WEIGHTS_IN_EXACT_RESUME_REQUIRED = True
ADAPTIVE_REWEIGHTING_DURING_TRAINING_AUTHORIZED = False
RUNTIME_WEIGHT_REDERIVATION_AFTER_TRAINING_START_AUTHORIZED = False
EXACT_RESUME_REQUIRED = True
OWNED_V2_DATA_REQUIRED = True
SCOPED_CHECKPOINT_CREATION_AUTHORIZED = True
COMPLETE_HELDOUT_AUDIO_REQUIRED = True
HUMAN_LISTENING_REQUIRED_FOR_ACCEPTANCE = True

GENERAL_PERSISTENT_TRAINING_AUTHORIZED = False
GENERAL_OPTIMIZER_CREATION_AUTHORIZED = False
THIRD_PARTY_MODEL_OR_CHECKPOINT_AUTHORIZED = False
PREDICTED_DURATION_MODIFICATION_AUTHORIZED = False
POSTHOC_GAIN_NORMALIZATION_AUTHORIZED = False
POSTHOC_EQ_AUTHORIZED = False
POSTHOC_DENOISING_AUTHORIZED = False
METRICS_CAN_ACCEPT_VOICE_QUALITY = False


def require_authorized_run(max_updates: int) -> None:
    if not TRAIN_AND_LISTEN_AUTHORIZED:
        raise RuntimeError("minimum-phase bounded train-and-listen route is not authorized")
    if max_updates < 1 or max_updates > MAX_UPDATES_AUTHORIZED:
        raise RuntimeError(
            f"minimum-phase candidate is authorized for 1..{MAX_UPDATES_AUTHORIZED} updates"
        )


__all__ = [
    "CONTRACT_VERSION",
    "POLICY_ID",
    "CPU_ONLY",
    "TRAIN_AND_LISTEN_AUTHORIZED",
    "MAX_UPDATES_AUTHORIZED",
    "DIRECTIONAL_PRETRAIN_CALIBRATION_REQUIRED",
    "CALIBRATION_BEFORE_MODEL_OPTIMIZER_REQUIRED",
    "CALIBRATED_WEIGHTS_FIXED_FOR_RUN",
    "CALIBRATED_WEIGHTS_IN_EXACT_RESUME_REQUIRED",
    "ADAPTIVE_REWEIGHTING_DURING_TRAINING_AUTHORIZED",
    "RUNTIME_WEIGHT_REDERIVATION_AFTER_TRAINING_START_AUTHORIZED",
    "EXACT_RESUME_REQUIRED",
    "SCOPED_CHECKPOINT_CREATION_AUTHORIZED",
    "COMPLETE_HELDOUT_AUDIO_REQUIRED",
    "HUMAN_LISTENING_REQUIRED_FOR_ACCEPTANCE",
    "THIRD_PARTY_MODEL_OR_CHECKPOINT_AUTHORIZED",
    "PREDICTED_DURATION_MODIFICATION_AUTHORIZED",
    "POSTHOC_GAIN_NORMALIZATION_AUTHORIZED",
    "POSTHOC_EQ_AUTHORIZED",
    "POSTHOC_DENOISING_AUTHORIZED",
    "METRICS_CAN_ACCEPT_VOICE_QUALITY",
    "require_authorized_run",
]
